CREATE DATABASE ANIVERSARIOS;
USE ANIVERSARIOS;

CREATE TABLE PESSOA(
	ID_PESSOA INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SOBRENOME VARCHAR(30) NOT NULL
);

CREATE TABLE ANIVERSARIO(
	ID_ANIVERSARIO INT PRIMARY KEY AUTO_INCREMENT,
	DIA INT NOT NULL,
	MES INT NOT NULL,
	ANO INT NOT NULL,
	ID_PESSOA INT UNIQUE,
	FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(ID_PESSOA)
);

CREATE VIEW VW_IDADE AS 
SELECT A.ID_PESSOA, IF(MONTH(NOW()) - A.MES < 0 OR (MONTH(NOW()) - A.MES = 0 AND (SELECT DAY(NOW())) < A.DIA), YEAR(NOW()) - A.ANO -1, YEAR(NOW()) - A.ANO) AS IDADE
FROM ANIVERSARIO A;

DELIMITER $

CREATE PROCEDURE CAD_PESSOA(P_NOME VARCHAR(30), P_SOBRENOME VARCHAR(30), P_DIA INT, P_MES INT, P_ANO INT)
BEGIN
	INSERT INTO PESSOA VALUES(NULL, UPPER(P_NOME), UPPER(P_SOBRENOME));
	INSERT INTO ANIVERSARIO
	VALUES (NULL, P_DIA, P_MES, P_ANO, (SELECT MAX(ID_PESSOA) FROM PESSOA));
END$

CREATE PROCEDURE RELATORIO_DIA(P_DIA INT)
BEGIN
	SELECT CONCAT(P.NOME, ' ', P.SOBRENOME) AS NOME, CONCAT(IF(A.DIA < 10, CONCAT('0', A.DIA) , A.DIA), '/', IF(A.MES < 10, CONCAT('0', A.MES) , A.MES), '/', A.ANO) AS NASCIMENTO, I.IDADE AS IDADE
	FROM PESSOA P
		INNER JOIN ANIVERSARIO A
		ON P.ID_PESSOA = A.ID_PESSOA
		INNER JOIN VW_IDADE I
		ON P.ID_PESSOA = I.ID_PESSOA
	WHERE A.DIA = P_DIA
	ORDER BY A.MES;
END$

CREATE PROCEDURE RELATORIO_MES(P_MES INT)
BEGIN
	SELECT CONCAT(P.NOME, ' ', P.SOBRENOME) AS NOME, CONCAT(IF(A.DIA < 10, CONCAT('0', A.DIA) , A.DIA), '/', IF(A.MES < 10, CONCAT('0', A.MES) , A.MES), '/', A.ANO) AS NASCIMENTO, I.IDADE AS IDADE
	FROM PESSOA P
		INNER JOIN ANIVERSARIO A
		ON P.ID_PESSOA = A.ID_PESSOA
		INNER JOIN VW_IDADE I
		ON P.ID_PESSOA = I.ID_PESSOA
	WHERE A.MES = P_MES
	ORDER BY A.DIA;
END$

CREATE PROCEDURE RELATORIO_ANO(P_ANO INT)
BEGIN
	SELECT CONCAT(P.NOME, ' ', P.SOBRENOME) AS NOME, CONCAT(IF(A.DIA < 10, CONCAT('0', A.DIA) , A.DIA), '/', IF(A.MES < 10, CONCAT('0', A.MES) , A.MES), '/', A.ANO) AS NASCIMENTO, I.IDADE AS IDADE
	FROM PESSOA P
		INNER JOIN ANIVERSARIO A
		ON P.ID_PESSOA = A.ID_PESSOA
		INNER JOIN VW_IDADE I
		ON P.ID_PESSOA = I.ID_PESSOA
	WHERE A.ANO = P_ANO
	ORDER BY A.MES, A.DIA;
END$

CREATE PROCEDURE RELATORIO_DIA_MES(P_DIA INT, P_MES INT)
BEGIN
	SELECT CONCAT(P.NOME, ' ', P.SOBRENOME) AS NOME, CONCAT(IF(A.DIA < 10, CONCAT('0', A.DIA) , A.DIA), '/', IF(A.MES < 10, CONCAT('0', A.MES) , A.MES), '/', A.ANO) AS NASCIMENTO, I.IDADE AS IDADE
	FROM PESSOA P
		INNER JOIN ANIVERSARIO A
		ON P.ID_PESSOA = A.ID_PESSOA
		INNER JOIN VW_IDADE I
		ON P.ID_PESSOA = I.ID_PESSOA
	WHERE A.DIA = P_DIA AND A.MES = P_MES
	ORDER BY A.MES, A.DIA;
END$

CREATE PROCEDURE RELATORIO_DIA_ANO(P_DIA INT, P_ANO INT)
BEGIN
	SELECT CONCAT(P.NOME, ' ', P.SOBRENOME) AS NOME, CONCAT(IF(A.DIA < 10, CONCAT('0', A.DIA) , A.DIA), '/', IF(A.MES < 10, CONCAT('0', A.MES) , A.MES), '/', A.ANO) AS NASCIMENTO, I.IDADE AS IDADE
	FROM PESSOA P
		INNER JOIN ANIVERSARIO A
		ON P.ID_PESSOA = A.ID_PESSOA
		INNER JOIN VW_IDADE I
		ON P.ID_PESSOA = I.ID_PESSOA
	WHERE A.DIA = P_DIA AND A.ANO = P_ANO
	ORDER BY A.MES, A.DIA;
END$

CREATE PROCEDURE RELATORIO_MES_ANO(P_mes INT, P_ANO INT)
BEGIN
	SELECT CONCAT(P.NOME, ' ', P.SOBRENOME) AS NOME, CONCAT(IF(A.DIA < 10, CONCAT('0', A.DIA) , A.DIA), '/', IF(A.MES < 10, CONCAT('0', A.MES) , A.MES), '/', A.ANO) AS NASCIMENTO, I.IDADE AS IDADE
	FROM PESSOA P
		INNER JOIN ANIVERSARIO A
		ON P.ID_PESSOA = A.ID_PESSOA
		INNER JOIN VW_IDADE I
		ON P.ID_PESSOA = I.ID_PESSOA
	WHERE A.MES = P_MES AND A.ANO = P_ANO
	ORDER BY A.MES, A.DIA;
END$

CREATE PROCEDURE RELATORIO_DATA(P_DIA INT, P_MES INT, P_ANO INT)
BEGIN
	SELECT CONCAT(P.NOME, ' ', P.SOBRENOME) AS NOME, CONCAT(IF(A.DIA < 10, CONCAT('0', A.DIA) , A.DIA), '/', IF(A.MES < 10, CONCAT('0', A.MES) , A.MES), '/', A.ANO) AS NASCIMENTO, I.IDADE AS IDADE
	FROM PESSOA P
		INNER JOIN ANIVERSARIO A
		ON P.ID_PESSOA = A.ID_PESSOA
		INNER JOIN VW_IDADE I
		ON P.ID_PESSOA = I.ID_PESSOA
	WHERE A.DIA = P_DIA AND A.MES = P_MES AND A.ANO = P_ANO
	ORDER BY A.MES, A.DIA;
END$

CREATE PROCEDURE REMOVE_PESSOA(P_ID_PESSOA INT)
BEGIN 
	DELETE FROM ANIVERSARIO WHERE ID_PESSOA = P_ID_PESSOA;
	DELETE FROM PESSOA WHERE ID_PESSOA = P_ID_PESSOA;
END$

CREATE PROCEDURE RELATORIO_GERAL(P_TP_ORDENACAO INT)
BEGIN
	CASE P_TP_ORDENACAO
		WHEN 1 THEN
			SELECT  P.ID_PESSOA AS ID, 
					CONCAT(P.NOME, ' ', P.SOBRENOME) AS NOME, 
					A.ID_ANIVERSARIO AS ID, 
					CONCAT(IF(A.DIA < 10, CONCAT('0', A.DIA) , A.DIA), '/', IF(A.MES < 10, CONCAT('0', A.MES) , A.MES), '/', A.ANO) AS NASCIMENTO, 
					I.IDADE AS IDADE, 
					A.ID_PESSOA AS 'ID PESSOA'
			FROM PESSOA P
				INNER JOIN ANIVERSARIO A
				ON P.ID_PESSOA = A.ID_PESSOA
				INNER JOIN VW_IDADE I
				ON P.ID_PESSOA = I.ID_PESSOA;
				
		WHEN 2 THEN
			SELECT  P.ID_PESSOA AS ID, 
					CONCAT(P.NOME, ' ', P.SOBRENOME) AS NOME, 
					A.ID_ANIVERSARIO AS ID, 
					CONCAT(IF(A.DIA < 10, CONCAT('0', A.DIA) , A.DIA), '/', IF(A.MES < 10, CONCAT('0', A.MES) , A.MES), '/', A.ANO) AS NASCIMENTO, 
					I.IDADE AS IDADE, 
					A.ID_PESSOA AS 'ID PESSOA'
			FROM PESSOA P
				INNER JOIN ANIVERSARIO A
				ON P.ID_PESSOA = A.ID_PESSOA
				INNER JOIN VW_IDADE I
				ON P.ID_PESSOA = I.ID_PESSOA
			ORDER BY A.DIA;
				
		WHEN 3 THEN
			SELECT  P.ID_PESSOA AS ID, 
					CONCAT(P.NOME, ' ', P.SOBRENOME) AS NOME, 
					A.ID_ANIVERSARIO AS ID, 
					CONCAT(IF(A.DIA < 10, CONCAT('0', A.DIA) , A.DIA), '/', IF(A.MES < 10, CONCAT('0', A.MES) , A.MES), '/', A.ANO) AS NASCIMENTO, 
					I.IDADE AS IDADE, 
					A.ID_PESSOA AS 'ID PESSOA'
			FROM PESSOA P
				INNER JOIN ANIVERSARIO A
				ON P.ID_PESSOA = A.ID_PESSOA
				INNER JOIN VW_IDADE I
				ON P.ID_PESSOA = I.ID_PESSOA
			ORDER BY A.MES;
		
		WHEN 4 THEN
			SELECT  P.ID_PESSOA AS ID, 
					CONCAT(P.NOME, ' ', P.SOBRENOME) AS NOME, 
					A.ID_ANIVERSARIO AS ID, 
					CONCAT(IF(A.DIA < 10, CONCAT('0', A.DIA) , A.DIA), '/', IF(A.MES < 10, CONCAT('0', A.MES) , A.MES), '/', A.ANO) AS NASCIMENTO, 
					I.IDADE AS IDADE, 
					A.ID_PESSOA AS 'ID PESSOA'
			FROM PESSOA P
				INNER JOIN ANIVERSARIO A
				ON P.ID_PESSOA = A.ID_PESSOA
				INNER JOIN VW_IDADE I
				ON P.ID_PESSOA = I.ID_PESSOA
			ORDER BY A.ANO;
			
		WHEN 5 THEN
			SELECT  P.ID_PESSOA AS ID, 
					CONCAT(P.NOME, ' ', P.SOBRENOME) AS NOME, 
					A.ID_ANIVERSARIO AS ID, 
					CONCAT(IF(A.DIA < 10, CONCAT('0', A.DIA) , A.DIA), '/', IF(A.MES < 10, CONCAT('0', A.MES) , A.MES), '/', A.ANO) AS NASCIMENTO, 
					I.IDADE AS IDADE, 
					A.ID_PESSOA AS 'ID PESSOA'
			FROM PESSOA P
				INNER JOIN ANIVERSARIO A
				ON P.ID_PESSOA = A.ID_PESSOA
				INNER JOIN VW_IDADE I
				ON P.ID_PESSOA = I.ID_PESSOA
			ORDER BY A.ANO, A.MES, A.DIA;
				
		WHEN 6 THEN
			SELECT  P.ID_PESSOA AS ID, 
			CONCAT(P.NOME, ' ', P.SOBRENOME) AS NOME, 
			A.ID_ANIVERSARIO AS ID, 
			CONCAT(IF(A.DIA < 10, CONCAT('0', A.DIA) , A.DIA), '/', IF(A.MES < 10, CONCAT('0', A.MES) , A.MES), '/', A.ANO) AS NASCIMENTO, 
			I.IDADE AS IDADE, 
			A.ID_PESSOA AS 'ID PESSOA'
			FROM PESSOA P
				INNER JOIN ANIVERSARIO A
				ON P.ID_PESSOA = A.ID_PESSOA
				INNER JOIN VW_IDADE I
				ON P.ID_PESSOA = I.ID_PESSOA
			ORDER BY P.NOME;
		
		WHEN 7 THEN
			SELECT  P.ID_PESSOA AS ID, 
					CONCAT(P.NOME, ' ', P.SOBRENOME) AS NOME, 
					A.ID_ANIVERSARIO AS ID, 
					CONCAT(IF(A.DIA < 10, CONCAT('0', A.DIA) , A.DIA), '/', IF(A.MES < 10, CONCAT('0', A.MES) , A.MES), '/', A.ANO) AS NASCIMENTO, 
					I.IDADE AS IDADE, 
					A.ID_PESSOA AS 'ID PESSOA'
			FROM PESSOA P
				INNER JOIN ANIVERSARIO A
				ON P.ID_PESSOA = A.ID_PESSOA
				INNER JOIN VW_IDADE I
				ON P.ID_PESSOA = I.ID_PESSOA
			ORDER BY P.SOBRENOME;
		
		WHEN 8 THEN
			SELECT  CONCAT(P.NOME, ' ', P.SOBRENOME) AS NOME,  
					CONCAT(IF(A.DIA < 10, CONCAT('0', A.DIA) , A.DIA), '/', IF(A.MES < 10, CONCAT('0', A.MES) , A.MES), '/', A.ANO) AS NASCIMENTO, 
					I.IDADE AS IDADE 
			FROM PESSOA P
				INNER JOIN ANIVERSARIO A
				ON P.ID_PESSOA = A.ID_PESSOA
				INNER JOIN VW_IDADE I
				ON P.ID_PESSOA = I.ID_PESSOA
			ORDER BY P.NOME, P.SOBRENOME;
			
		WHEN 9 THEN
			SELECT  CONCAT(P.NOME, ' ', P.SOBRENOME) AS NOME, 
					CONCAT(IF(A.DIA < 10, CONCAT('0', A.DIA) , A.DIA), '/', IF(A.MES < 10, CONCAT('0', A.MES) , A.MES), '/', A.ANO) AS NASCIMENTO, 
					I.IDADE AS IDADE
			FROM PESSOA P
				INNER JOIN ANIVERSARIO A
				ON P.ID_PESSOA = A.ID_PESSOA
				INNER JOIN VW_IDADE I
				ON P.ID_PESSOA = I.ID_PESSOA
			ORDER BY I.IDADE;
		
		WHEN 10 THEN
			SELECT  CONCAT(P.NOME, ' ', P.SOBRENOME) AS NOME, 
					CONCAT(IF(A.DIA < 10, CONCAT('0', A.DIA) , A.DIA), '/', IF(A.MES < 10, CONCAT('0', A.MES) , A.MES), '/', A.ANO) AS NASCIMENTO, 
					I.IDADE AS IDADE
			FROM PESSOA P
				INNER JOIN ANIVERSARIO A
				ON P.ID_PESSOA = A.ID_PESSOA
				INNER JOIN VW_IDADE I
				ON P.ID_PESSOA = I.ID_PESSOA
			ORDER BY I.IDADE DESC;
		
		WHEN 11 THEN
		
			SELECT  CONCAT(P.NOME, ' ', P.SOBRENOME) AS NOME, 
					CONCAT(IF(A.DIA < 10, CONCAT('0', A.DIA) , A.DIA), '/', IF(A.MES < 10, CONCAT('0', A.MES) , A.MES), '/', A.ANO) AS NASCIMENTO, 
					I.IDADE AS IDADE
			FROM PESSOA P
				INNER JOIN ANIVERSARIO A
				ON P.ID_PESSOA = A.ID_PESSOA
				INNER JOIN VW_IDADE I
				ON P.ID_PESSOA = I.ID_PESSOA
			WHERE P.ID_PESSOA = (SELECT ID_PESSOA FROM VW_IDADE WHERE IDADE = (SELECT MIN(IDADE) FROM VW_IDADE))
			UNION
			SELECT  CONCAT(P.NOME, ' ', P.SOBRENOME) AS NOME, 
					CONCAT(IF(A.DIA < 10, CONCAT('0', A.DIA) , A.DIA), '/', IF(A.MES < 10, CONCAT('0', A.MES) , A.MES), '/', A.ANO) AS NASCIMENTO, 
					I.IDADE AS IDADE
			FROM PESSOA P
				INNER JOIN ANIVERSARIO A
				ON P.ID_PESSOA = A.ID_PESSOA
				INNER JOIN VW_IDADE I
				ON P.ID_PESSOA = I.ID_PESSOA
			WHERE P.ID_PESSOA = (SELECT ID_PESSOA FROM VW_IDADE WHERE IDADE = (SELECT MAX(IDADE) FROM VW_IDADE))
			UNION
			SELECT '','',''
			UNION
			SELECT 'MÉDIA DE', 'IDADE DAS', 'PESSOAS'
			UNION
			SELECT '*****', '*****', FORMAT(AVG(IDADE), 2) FROM VW_IDADE;
		
	END CASE;
END$

CREATE PROCEDURE BUSCA_PESSOA(P_NOME VARCHAR(60))
BEGIN
	SELECT  P.ID_PESSOA AS ID, 
			CONCAT(P.NOME, ' ', P.SOBRENOME) AS NOME, 
			CONCAT(IF(A.DIA < 10, CONCAT('0', A.DIA) , A.DIA), '/', IF(A.MES < 10, CONCAT('0', A.MES) , A.MES), '/', A.ANO) AS NASCIMENTO, 
			I.IDADE AS IDADE
	FROM PESSOA P
		INNER JOIN ANIVERSARIO A
		ON P.ID_PESSOA = A.ID_PESSOA
		INNER JOIN VW_IDADE I
		ON P.ID_PESSOA = I.ID_PESSOA
	WHERE CONCAT(P.NOME, ' ', P.SOBRENOME) LIKE CONCAT('%', P_NOME, '%')
	ORDER BY P.NOME, P.SOBRENOME;
END$

DELIMITER ;

/* TRAZ OS ANIVERSÁRIANTES DO DIA ESCOLHIDO */
CALL RELATORIO_DIA(23);

/* TRAZ OS ANIVERSÁRIANTES DO MÊS ESCOLHIDO */
CALL RELATORIO_MES(9);

/* TRAZ AS PESSOAS QUE NASCERAM NO ANO ESCOLHIDO */
CALL RELATORIO_ANO(1966);

/* TRAZ AS PESSOAS QUE NASCERAM NO DIA E MÊS ESCOLHIDOS */
CALL RELATORIO_DIA_MES(5, 9);

/* TRAZ AS PESSOAS QUE NASCERAM NO DIA E ANO ESCOLHIDOS */
CALL RELATORIO_DIA_ANO(5, 1966);

/* TRAZ AS PESSOAS QUE NASCERAM NO MES E ANO ESCOLHIDOS */
CALL RELATORIO_MES_ANO(5, 1966);

/* TRAZ AS PESSOAS QUE NASCERAM NA DATA ESCOLHIDA */
CALL RELATORIO_DATA(5, 9, 1966);

/* TRAZ UM RELATORIO CONFORME O TIPO ESCOLHIDO 
	1 - RELATORIO COM TODOS OS CAMPOS, NA ORDEM QUE FORAM CADASTRADOS
	2 - RELATORIO COM TODOS OS CAMPOS, ORDENADO POR DIA DE NASCIMENTO
	3 - RELATORIO COM TODOS OS CAMPOS, ORDENADO POR MÊS DE NASCIMENTO 
	4 - RELATORIO COM TODOS OS CAMPOS, ORDENADO POR ANO DE NASCIMENTO
	5 - RELATORIO COM TODOS OS CAMPOS, ORDENADO POR ANO, MÊS E DIA DE NASCIMENTO
	6 - RELATORIO COM TODOS OS CAMPOS, ORDENAOD POR NOME
	7 - RELATORIO COM TODOS OS CAMPOS, ORDENADO POR SOBRENOME
	8 - TODOS OS CAMPOS(MENOS OS DE ID), ORDENADOS POR NOME E SOBRENOME
	9 - TODOS OS CAMPOS (MENOS OS DE ID), ORDENADOS POR IDADE
	10 - TODOS OS CAMPOS (MENOS OS DE ID), ORDENADOS POR IDADE (DECRESCENTE)
	11 - MENOR IDADE, MAIOR IDADE E MÉDIA DE IDADE DAS PESSOAS DA TABELA
*/
CALL RELATORIO_GERAL(9);

/* REMOVE UMA PESSOA E O SEU ANIVERSÁRIO COM BASE NO ID DA PESSOA */
CALL REMOVE_PESSOA(1);

/* BUSCA POR PESSOAS QUE TENHA ESSE NOME OU ESSE TRECHO DE NOME */
CALL BUSCA_PESSOA('MARCELO');

/* CADASTRA A PESSOA E O ANIVERSÁRIO */
CALL CAD_PESSOA('FULANO', 'DE TAL', 5, 9, 1966);
